<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-3ND57S0" name="com.jusdone.qa.testcases.LoginPageTest" tests="8" failures="1" timestamp="06 Feb 2018 03:20:21 GMT" time="84.877" errors="0">
  <testcase name="verifyLoginNameTest" time="9.487" classname="com.jusdone.qa.testcases.LoginPageTest"/>
  <testcase name="verifyLoginBtnTest" time="8.872" classname="com.jusdone.qa.testcases.LoginPageTest"/>
  <testcase name="verifyForgotPasswordTest" time="9.787" classname="com.jusdone.qa.testcases.LoginPageTest"/>
  <testcase name="verifyCtrAnAcctTest" time="9.715" classname="com.jusdone.qa.testcases.LoginPageTest"/>
  <testcase name="verifyRememberMeTest" time="8.624" classname="com.jusdone.qa.testcases.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.jusdone.qa.testcases.LoginPageTest.verifyRememberMeTest(LoginPageTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyRememberMeTest -->
  <testcase name="ValidLoginTest" time="13.973" classname="com.jusdone.qa.testcases.LoginPageTest"/>
  <testcase name="InValidLoginTest" time="10.082" classname="com.jusdone.qa.testcases.LoginPageTest"/>
  <testcase name="BlankEmailTest" time="14.337" classname="com.jusdone.qa.testcases.LoginPageTest"/>
</testsuite> <!-- com.jusdone.qa.testcases.LoginPageTest -->
